
USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS TRANSFORM_DATA;

GRANT ROLE TRANSFORM_DATA TO ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS PURAN_WH;

GRANT OPERATE ON WAREHOUSE PURAN_WH TO ROLE TRANSFORM_DATA;


CREATE USER IF NOT EXISTS dbt
  PASSWORD='dbtPassword123'
  LOGIN_NAME='dbt'
  MUST_CHANGE_PASSWORD=FALSE
  DEFAULT_WAREHOUSE='PURAN_WH'
  DEFAULT_ROLE=TRANSFORM_DATA
  DEFAULT_NAMESPACE='NETFLIX.RAW'
  COMMENT='DBT user used for data transformation';
ALTER USER dbt SET TYPE = PERSON;
GRANT ROLE TRANSFORM_DATA TO USER dbt;


CREATE DATABASE IF NOT EXISTS NETFLIX;
CREATE SCHEMA IF NOT EXISTS NETFLIX.RAW;


GRANT ALL ON WAREHOUSE PURAN_WH TO ROLE TRANSFORM_DATA;
GRANT ALL ON DATABASE NETFLIX TO ROLE TRANSFORM_DATA;
GRANT ALL ON ALL SCHEMAS IN DATABASE NETFLIX TO ROLE TRANSFORM_DATA;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE NETFLIX TO ROLE TRANSFORM_DATA;
GRANT ALL ON ALL TABLES IN SCHEMA NETFLIX.RAW TO ROLE TRANSFORM_DATA;
GRANT ALL ON FUTURE TABLES IN SCHEMA NETFLIX.RAW TO ROLE TRANSFORM_DATA;



